"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

"""Build paths inside the project like this: BASE_DIR / 'subdir'."""
BASE_DIR = Path(__file__).resolve().parent.parent

"""
Load environment variables from a local .env file (not committed).
See .env.template for the expected keys.
"""
load_dotenv(BASE_DIR / '.env')


def env_bool(name, default=False):
    """Read a boolean-ish environment variable ('1', 'true', 'yes', 'on')."""
    return os.environ.get(name, str(default)).strip().lower() in {
        '1', 'true', 'yes', 'on',
    }


"""
Quick-start development settings - unsuitable for production
See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/
"""

"""SECURITY WARNING: keep the secret key used in production secret!"""
SECRET_KEY = os.environ['DJANGO_SECRET_KEY']

"""SECURITY WARNING: don't run with debug turned on in production!"""
DEBUG = env_bool('DJANGO_DEBUG', default=False)

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get('DJANGO_ALLOWED_HOSTS', '').split(',')
    if host.strip()
]

"""Application definition"""

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'django_filters',
    'auth_app',
    'profile_app',
    'offers_app',
    'orders_app',
    'reviews_app',
    'base_info_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

"""
Database
https://docs.djangoproject.com/en/6.0/ref/settings/#databases
"""

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

"""
Password validation
https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators
"""

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

"""
Internationalization
https://docs.djangoproject.com/en/6.0/topics/i18n/
"""

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

"""
Static files (CSS, JavaScript, Images)
https://docs.djangoproject.com/en/6.0/howto/static-files/
"""

STATIC_URL = 'static/'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

"""
No global pagination: the Coderr frontend expects plain arrays from the
list endpoints (profiles, reviews, orders). Only GET /api/offers/ is
paginated, via OfferPagination set explicitly on OfferListCreateView.
"""
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
    ],
}

"""The frontend runs on a different port (e.g. Live Server), so allow CORS."""
CORS_ALLOW_ALL_ORIGINS = True
